// Bundles ./public into src/site.gen.ts so the Worker serves the site itself.
// (Workers Static Assets needs a separate upload step that some CI / proxy setups can't do; the site is ~70 KB.)
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
};
const dir = new URL('../public/', import.meta.url).pathname;
const names = readdirSync(dir).sort().filter((name) => TYPES[extname(name)]);

// Cache busting: pages reference scripts, styles and images as /file.js?v=<content hash>, so every deploy
// is picked up at once even by browsers that cached the previous files (the Worker caches ?v= URLs for long).
const versions = Object.fromEntries(
  names.map((name) => [name, createHash('sha256').update(readFileSync(join(dir, name))).digest('hex').slice(0, 10)]),
);
const versioned = (html) =>
  html.replace(/(src|href)="\/([\w.-]+\.(?:js|css|svg|png))"/g, (all, attr, file) =>
    versions[file] ? `${attr}="/${file}?v=${versions[file]}"` : all,
  );

const files = {};
for (const name of names) {
  const type = TYPES[extname(name)];
  let buf = readFileSync(join(dir, name));
  if (type.startsWith('text/html')) buf = Buffer.from(versioned(buf.toString('utf8')));
  // Unfilled template fields (e.g. {{ADDRESS}} in tokushoho.html) must never go live.
  const unfilled = type.startsWith('text/html') && buf.toString('utf8').match(/\{\{[A-Z_]+\}\}/g);
  if (unfilled) throw new Error(`${name} has unfilled fields: ${[...new Set(unfilled)].join(', ')}`);
  files[`/${name}`] = type.startsWith('image/png') ? { type, base64: buf.toString('base64') } : { type, text: buf.toString('utf8') };
}
writeFileSync(
  new URL('../src/site.gen.ts', import.meta.url),
  `// Generated by scripts/embed.mjs from ./public. Do not edit.\nexport const SITE: Record<string, { type: string; text?: string; base64?: string }> = ${JSON.stringify(files, null, 1)};\n`,
);
console.log(`embedded ${Object.keys(files).length} files`);
