// Bundles ./public into src/site.gen.ts so the Worker serves the site itself.
// (Workers Static Assets needs a separate upload step that some CI / proxy setups can't do; the site is ~70 KB.)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
};
const dir = new URL('../public/', import.meta.url).pathname;
const files = {};
for (const name of readdirSync(dir).sort()) {
  const type = TYPES[extname(name)];
  if (!type) continue;
  const buf = readFileSync(join(dir, name));
  // Unfilled template fields (e.g. {{ADDRESS}} in tokushoho.html) must never go live.
  const unfilled = type.startsWith('text/html') && buf.toString('utf8').match(/\{\{[A-Z_]+\}\}/g);
  if (unfilled) throw new Error(`${name} has unfilled fields: ${[...new Set(unfilled)].join(', ')}`);
  files[`/${name}`] = type.startsWith('image/png') ? { type, base64: buf.toString('base64') } : { type, text: buf.toString('utf8') };
}
writeFileSync(
  new URL('../src/site.gen.ts', import.meta.url),
  `// Generated by scripts/embed.mjs from ./public. Do not edit.\nexport const SITE: Record<string, { type: string; text?: string; base64?: string }> = ${JSON.stringify(files, null, 1)};\n`,
);
console.log(`embedded ${Object.keys(files).length} files`);
